
const NAV=[['dashboard','⌂','Dashboard'],['clients','♙','Clients'],['quotes','▤','Quotes'],['invoices','▥','Invoices'],['schedule','▦','Schedule']];
const KEY='showpay_artist_final_v1';
const DEFAULT={settings:{name:'ShowPay Artist',vat:'',address:'',email:'',phone:'',bank:'',account:'Cheque',accNo:'',branch:'',terms:'Valid for 30 days. Booking is confirmed once the required deposit is received. Balance payable before or on the performance date.'},clients:[],quotes:[],invoices:[],events:[]};
let db=load();let quoteItems=[];let invoiceItems=[];let currentQuote=null;let currentInvoice=null;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(DEFAULT)}catch(e){return structuredClone(DEFAULT)}}
function save(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function money(n){return 'R'+Number(n||0).toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2})}
function dateFmt(v){if(!v)return '-';return new Date(v+'T00:00:00').toLocaleDateString('en-ZA',{day:'2-digit',month:'short',year:'numeric'})}
function today(){return new Date().toISOString().slice(0,10)}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function navBuild(){for(const [id,ic,label] of NAV){document.getElementById('sideNav').insertAdjacentHTML('beforeend',`<button data-page="${id}" onclick="openPage('${id}')"><span class="ico">${ic}</span>${label}</button>`);document.getElementById('mobileNav').insertAdjacentHTML('beforeend',`<button data-page="${id}" onclick="openPage('${id}')"><span>${ic}</span>${label}</button>`)} }
function openPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active','printing'));const el=document.getElementById(id);if(!el)return;el.classList.add('active');document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===id));document.getElementById('topTitle').textContent=el.querySelector('h1,h2')?.textContent||'ShowPay Artist';window.scrollTo(0,0)}
function nextNo(type){const arr=type==='quote'?db.quotes:db.invoices;return `${type==='quote'?'QUO':'INV'}-${String(arr.length+1).padStart(4,'0')}`}
function client(id){return db.clients.find(c=>String(c.id)===String(id))||{name:'Client',contact:'',email:'',phone:'',address:'',vat:''}}
function subtotal(items){return items.reduce((s,i)=>s+(Number(i.qty)||0)*(Number(i.price)||0),0)}
function vatRate(){return db.settings.vat?15:0}
function addClientInline(){showClientForm();document.getElementById('cName').focus()}
function showClientForm(){document.getElementById('clientFormCard').style.display='block'}function hideClientForm(){document.getElementById('clientFormCard').style.display='none'}
function saveClient(){const name=document.getElementById('cName').value.trim();if(!name){alert('Client / Company name is required.');return}db.clients.push({id:Date.now(),name,contact:document.getElementById('cContact').value.trim(),email:document.getElementById('cEmail').value.trim(),phone:document.getElementById('cPhone').value.trim(),address:document.getElementById('cAddress').value.trim(),vat:document.getElementById('cVat').value.trim(),type:document.getElementById('cType').value});['cName','cContact','cEmail','cPhone','cAddress','cVat'].forEach(id=>document.getElementById(id).value='');hideClientForm();save();toast('Client saved')}
function deleteClient(id){if(confirm('Delete this client?')){db.clients=db.clients.filter(c=>c.id!==id);save();toast('Client deleted')}}
function renderClients(){const body=document.getElementById('clientRows');body.innerHTML=db.clients.length?db.clients.map(c=>`<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(c.contact)}</td><td>${esc(c.email)}</td><td>${esc(c.phone)}</td><td>${esc(c.type)}</td><td><button class="iconBtn" onclick="deleteClient(${c.id})">✕</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty">No clients yet. Add your first client.</td></tr>'}
function clientOptions(id){document.getElementById(id).innerHTML='<option value="">Select a client</option>'+db.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}
function blankItem(){return {desc:'Live Performance',qty:1,price:0}}
function drawItems(type){const arr=type==='q'?quoteItems:invoiceItems;const el=document.getElementById(type==='q'?'qItems':'iItems');el.innerHTML=arr.length?arr.map((x,i)=>`<div class="lineRow"><input value="${esc(x.desc)}" placeholder="Description" oninput="${type==='q'?'quoteItems':'invoiceItems'}[${i}].desc=this.value"><input type="number" min="0" step="1" value="${x.qty}" oninput="${type==='q'?'quoteItems':'invoiceItems'}[${i}].qty=Number(this.value);calcForm('${type}')"><input type="number" min="0" step="0.01" value="${x.price}" oninput="${type==='q'?'quoteItems':'invoiceItems'}[${i}].price=Number(this.value);calcForm('${type}')"><input readonly value="${money(x.qty*x.price)}"><button class="iconBtn" onclick="removeItem('${type}',${i})">✕</button></div>`).join(''):'<div class="empty">No line items.</div>';calcForm(type)}
function removeItem(type,i){(type==='q'?quoteItems:invoiceItems).splice(i,1);drawItems(type)}
function calcForm(type){const total=subtotal(type==='q'?quoteItems:invoiceItems);const vat=total*vatRate()/100;document.getElementById(type==='q'?'qSubtotal':'iSubtotal').textContent=money(total);document.getElementById(type==='q'?'qVat':'iVat').textContent=money(vat);document.getElementById(type==='q'?'qTotal':'iTotal').textContent=money(total+vat)}
function openQuote(){clientOptions('qClient');quoteItems=[blankItem()];document.getElementById('qNumber').value=nextNo('quote');document.getElementById('qDate').value=today();const d=new Date();d.setDate(d.getDate()+30);document.getElementById('qValid').value=d.toISOString().slice(0,10);document.getElementById('qTerms').value=db.settings.terms;drawItems('q');openPage('quote-form')}
function openInvoice(){clientOptions('iClient');invoiceItems=[blankItem()];document.getElementById('iNumber').value=nextNo('invoice');document.getElementById('iDate').value=today();const d=new Date();d.setDate(d.getDate()+7);document.getElementById('iDue').value=d.toISOString().slice(0,10);document.getElementById('iTerms').value=db.settings.terms;drawItems('i');openPage('invoice-form')}
function saveQuote(){const cid=document.getElementById('qClient').value;if(!cid){alert('Please select a client.');return}const itemCopy=JSON.parse(JSON.stringify(quoteItems));db.quotes.push({id:Date.now(),number:document.getElementById('qNumber').value,clientId:cid,date:document.getElementById('qDate').value,valid:document.getElementById('qValid').value,items:itemCopy,terms:document.getElementById('qTerms').value,status:'Open'});save();openPage('quotes');toast('Quote saved')}
function saveInvoice(){const cid=document.getElementById('iClient').value;if(!cid){alert('Please select a client.');return}const itemCopy=JSON.parse(JSON.stringify(invoiceItems));db.invoices.push({id:Date.now(),number:document.getElementById('iNumber').value,clientId:cid,date:document.getElementById('iDate').value,due:document.getElementById('iDue').value,items:itemCopy,terms:document.getElementById('iTerms').value,status:'Pending'});save();openPage('invoices');toast('Invoice saved')}
function pill(s){const c=s==='Paid'?'paid':s==='Overdue'?'overdue':s==='Open'?'open':s==='Draft'?'draft':'pending';return `<span class="pill ${c}">${esc(s)}</span>`}
function quoteTotal(q){return subtotal(q.items)*(1+vatRate()/100)}function invoiceTotal(i){return subtotal(i.items)*(1+vatRate()/100)}
function renderQuotes(){const body=document.getElementById('quoteRows');body.innerHTML=db.quotes.length?db.quotes.map(q=>`<tr><td><strong>${esc(q.number)}</strong></td><td>${esc(client(q.clientId).name)}</td><td>${dateFmt(q.date)}</td><td>${dateFmt(q.valid)}</td><td>${money(quoteTotal(q))}</td><td>${pill(q.status)}</td><td><button class="btn secondary" onclick="viewQuote(${q.id})">View</button> <button class="btn" onclick="convertQuote(${q.id})">Invoice</button></td></tr>`).join(''):'<tr><td colspan="7" class="empty">No quotes yet.</td></tr>'}
function renderInvoices(){const body=document.getElementById('invoiceRows');body.innerHTML=db.invoices.length?db.invoices.map(i=>`<tr><td><strong>${esc(i.number)}</strong></td><td>${esc(client(i.clientId).name)}</td><td>${dateFmt(i.date)}</td><td>${dateFmt(i.due)}</td><td>${money(invoiceTotal(i))}</td><td>${pill(i.status)}</td><td><button class="btn secondary" onclick="viewInvoice(${i.id})">View</button></td></tr>`).join(''):'<tr><td colspan="7" class="empty">No invoices yet.</td></tr>'}
function docHTML(type,obj){const c=client(obj.clientId), s=db.settings;const sub=subtotal(obj.items),vat=sub*vatRate()/100,total=sub+vat;const isQ=type==='quote';return `<div class="docHead"><div><img class="docLogo" src="assets/showpay-logo.svg"><div style="margin-top:8px;font-size:12px;line-height:1.5"><strong>${esc(s.name)}</strong><br>${esc(s.address)}<br>${esc(s.email)} · ${esc(s.phone)}${s.vat?'<br>VAT: '+esc(s.vat):''}</div></div><div style="text-align:right"><h2>${isQ?'QUOTATION':'INVOICE'}</h2><strong>${esc(obj.number)}</strong><br><span style="font-size:12px">Issue: ${dateFmt(obj.date)}<br>${isQ?'Valid until: '+dateFmt(obj.valid):'Due: '+dateFmt(obj.due)}</span></div></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:30px;margin-top:20px;font-size:13px"><div><strong>FROM</strong><br>${esc(s.name)}<br>${esc(s.address)}</div><div><strong>TO</strong><br>${esc(c.name)}<br>${esc(c.contact)}<br>${esc(c.address)}${c.vat?'<br>VAT: '+esc(c.vat):''}</div></div><table><thead><tr><th>Description</th><th>Qty</th><th class="right">Unit</th><th class="right">Total</th></tr></thead><tbody>${obj.items.map(i=>`<tr><td>${esc(i.desc)}</td><td>${i.qty}</td><td class="right">${money(i.price)}</td><td class="right">${money(i.qty*i.price)}</td></tr>`).join('')}</tbody></table><div class="docTotals"><div><span>Subtotal</span><strong>${money(sub)}</strong></div><div><span>VAT ${vatRate()?`(${vatRate()}%)`:'(not registered)'}</span><strong>${money(vat)}</strong></div><div class="grand"><span>${isQ?'Total':'Balance Due'}</span><strong>${money(total)}</strong></div></div><div class="docFoot"><strong>${isQ?'Terms & Conditions':'Payment Instructions'}</strong><br>${esc(obj.terms||s.terms)}${!isQ?`<br><br><strong>Banking Details</strong><br>${esc(s.bank)} · ${esc(s.account)} · Account ${esc(s.accNo)} · Branch ${esc(s.branch)}`:''}</div>`}
function viewQuote(id){currentQuote=db.quotes.find(q=>q.id===id);if(!currentQuote)return;document.getElementById('quoteDoc').innerHTML=docHTML('quote',currentQuote);openPage('quote-preview')}
function viewInvoice(id){currentInvoice=db.invoices.find(i=>i.id===id);if(!currentInvoice)return;document.getElementById('invoiceDoc').innerHTML=docHTML('invoice',currentInvoice);openPage('invoice-preview')}
function convertQuote(id){const q=db.quotes.find(x=>x.id===id);if(!q)return;db.invoices.push({id:Date.now(),number:nextNo('invoice'),clientId:q.clientId,date:today(),due:new Date(Date.now()+7*864e5).toISOString().slice(0,10),items:JSON.parse(JSON.stringify(q.items)),terms:q.terms,status:'Pending',fromQuote:q.number});q.status='Invoiced';save();openPage('invoices');toast('Quote converted to invoice')}
function addEvent(){const date=prompt('Event date (YYYY-MM-DD)',today());if(!date)return;const name=prompt('Event / performance name','Live Performance');if(!name)return;const venue=prompt('Venue','');const fee=prompt('Fee (ZAR)','0');const cid=db.clients.length?prompt('Client name (optional)',client(db.clients[0].id).name):'';db.events.push({id:Date.now(),date,name,venue,fee:Number(fee)||0,clientName:cid||''});save();toast('Event added')}
function renderEvents(){const sorted=[...db.events].sort((a,b)=>a.date.localeCompare(b.date));document.getElementById('eventRows').innerHTML=sorted.length?sorted.map(e=>`<tr><td>${dateFmt(e.date)}</td><td><strong>${esc(e.name)}</strong></td><td>${esc(e.clientName)}</td><td>${esc(e.venue)}</td><td>${money(e.fee)}</td><td><button class="iconBtn" onclick="deleteEvent(${e.id})">✕</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty">No events yet.</td></tr>';document.getElementById('dashEvents').innerHTML=sorted.slice(0,5).map(e=>`<tr><td>${dateFmt(e.date)}</td><td>${esc(e.name)}</td><td>${esc(e.clientName)}</td><td>${esc(e.venue)}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">Your upcoming performances will appear here.</td></tr>'}
function deleteEvent(id){if(confirm('Delete this event?')){db.events=db.events.filter(e=>e.id!==id);save()}}
function fillSettings(){const s=db.settings;[['sName','name'],['sVat','vat'],['sAddress','address'],['sEmail','email'],['sPhone','phone'],['sBank','bank'],['sAccount','account'],['sAccNo','accNo'],['sBranch','branch'],['sTerms','terms']].forEach(([a,b])=>document.getElementById(a).value=s[b]||'');document.getElementById('sideName').textContent=s.name||'ShowPay Artist'}
function saveSettings(){db.settings={name:document.getElementById('sName').value.trim()||'ShowPay Artist',vat:document.getElementById('sVat').value.trim(),address:document.getElementById('sAddress').value.trim(),email:document.getElementById('sEmail').value.trim(),phone:document.getElementById('sPhone').value.trim(),bank:document.getElementById('sBank').value.trim(),account:document.getElementById('sAccount').value.trim(),accNo:document.getElementById('sAccNo').value.trim(),branch:document.getElementById('sBranch').value.trim(),terms:document.getElementById('sTerms').value.trim()};save();fillSettings();toast('Settings saved')}
function renderAll(){renderClients();renderQuotes();renderInvoices();renderEvents();fillSettings();document.getElementById('statClients').textContent=db.clients.length;document.getElementById('statQuotes').textContent=db.quotes.filter(q=>q.status==='Open').length;document.getElementById('statInvoices').textContent=db.invoices.filter(i=>i.status!=='Paid').length;document.getElementById('statEvents').textContent=db.events.length}
function printDocument(type){document.querySelectorAll('.page').forEach(p=>p.classList.remove('printing'));const id=type==='quote'?'quote-preview':'invoice-preview';document.getElementById(id).classList.add('printing');setTimeout(()=>window.print(),50)}
navBuild();renderAll();
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}))}
